UPDATE gamesite.game_page SET proj_id = 14, img = '../img/hearthstone.jpg', video = 'https://www.youtube.com/embed/vPguoeYTvMI', about = 'Some text about this game should be placed here!' WHERE id = 1;
UPDATE gamesite.game_page SET proj_id = 16, img = '../img/hex.jpg', video = 'https://www.youtube.com/embed/5Ivz9MWhrHM', about = 'Some text about Hex game should be placed here!' WHERE id = 2;
UPDATE gamesite.game_page SET proj_id = 18, img = '../img/gwint.jpg', video = 'https://www.youtube.com/embed/5yu7FVZOyAo', about = 'Some text about Gwint gonna be placed here soon!' WHERE id = 4;
UPDATE gamesite.game_page_carousel SET proj_id = 14, carousel = 'http://via.placeholder.com/1920x1080?text=Game+1', carousel_title = 'Slider_1', carousel_info = 'Information 1' WHERE id = 1;
UPDATE gamesite.game_page_carousel SET proj_id = 14, carousel = 'http://via.placeholder.com/1920x1080?text=Game+2', carousel_title = 'Slider_2', carousel_info = 'Information 2' WHERE id = 2;
UPDATE gamesite.game_page_carousel SET proj_id = 14, carousel = 'http://via.placeholder.com/1920x1080?text=Game+3', carousel_title = 'Slider_3', carousel_info = 'Information 3' WHERE id = 3;
UPDATE gamesite.game_project SET proj_name = 'Hearthstone', proj_url = 'https://playhearthstone.com/ru-ru/', proj_img = 'img/hearthstone.jpg', proj_desc = 'Best TCG game... ', is_featured = true WHERE id = 14;
UPDATE gamesite.game_project SET proj_name = 'Hex ', proj_url = 'http://www.hextcg.com/', proj_img = 'img/hex.jpg', proj_desc = 'Cool tcg with nice UI...', is_featured = true WHERE id = 16;
UPDATE gamesite.game_project SET proj_name = 'gwint', proj_url = 'https://www.playgwent.com', proj_img = 'img/gwint.jpg', proj_desc = 'You know that stuff', is_featured = false WHERE id = 18;
UPDATE gamesite.game_project SET proj_name = 'Star Worlds', proj_url = 'http://starworlds.ru/', proj_img = 'img/star_worlds.jpg', proj_desc = 'Coming soon', is_featured = false WHERE id = 19;
UPDATE gamesite.game_project SET proj_name = 'Game 1', proj_url = 'http://via.placeholder.com/1920x1080?text=Game+1', proj_img = 'http://via.placeholder.com/1920x1080?text=Game+1', proj_desc = 'Game 1 description', is_featured = false WHERE id = 20;
UPDATE gamesite.game_project SET proj_name = 'Game 2', proj_url = 'http://via.placeholder.com/1920x1080?text=Game+2', proj_img = 'http://via.placeholder.com/1920x1080?text=Game+2', proj_desc = 'Game 2 description', is_featured = false WHERE id = 21;
UPDATE gamesite.game_project SET proj_name = 'Game 3', proj_url = 'http://via.placeholder.com/1920x1080?text=Game+3', proj_img = 'http://via.placeholder.com/1920x1080?text=Game+3', proj_desc = 'Game 3 description', is_featured = false WHERE id = 22;
UPDATE gamesite.game_project SET proj_name = 'Game 4', proj_url = 'http://via.placeholder.com/1920x1080?text=Game+4', proj_img = 'http://via.placeholder.com/1920x1080?text=Game+4', proj_desc = 'Game 4 description', is_featured = false WHERE id = 23;
UPDATE gamesite.game_project SET proj_name = 'Game 5', proj_url = 'http://via.placeholder.com/1920x1080?text=Game+5', proj_img = 'http://via.placeholder.com/1920x1080?text=Game+5', proj_desc = 'Game 5 description', is_featured = false WHERE id = 24;
UPDATE gamesite.proj_platform SET proj_id = 14, pc = true, android = true, ios = true, ps = true, xbox = true WHERE id = 1;
UPDATE gamesite.proj_service SET proj_id = 14, steam = null, gog = null, origin = null, ps_store = null, microsoft_xbox = null, google_play = true, app_store = true WHERE id = 1;
UPDATE gamesite.user_data SET user_id = 3, nickname = null, age = 18, region = 'eu', session_id = '4v78be05sf08i972u6rcmo3nd1' WHERE id = 1;
UPDATE gamesite.user_data SET user_id = 4, nickname = null, age = 18, region = 'eu', session_id = null WHERE id = 2;
UPDATE gamesite.user_data SET user_id = 7, nickname = null, age = 12, region = 'eu', session_id = null WHERE id = 5;
UPDATE gamesite.user_data SET user_id = 8, nickname = null, age = 18, region = 'eu', session_id = null WHERE id = 6;
UPDATE gamesite.user_data SET user_id = 9, nickname = null, age = 18, region = 'eu', session_id = null WHERE id = 7;
UPDATE gamesite.user_data SET user_id = 10, nickname = null, age = 18, region = 'eu', session_id = null WHERE id = 8;
UPDATE gamesite.user_role SET user_id = 3, role = 'admin' WHERE id = 1;
UPDATE gamesite.user_role SET user_id = 4, role = 'subscriber' WHERE id = 2;
UPDATE gamesite.user_role SET user_id = 7, role = 'subscriber' WHERE id = 5;
UPDATE gamesite.user_role SET user_id = 8, role = 'subscriber' WHERE id = 6;
UPDATE gamesite.user_role SET user_id = 9, role = 'subscriber' WHERE id = 7;
UPDATE gamesite.user_role SET user_id = 10, role = 'subscriber' WHERE id = 8;
UPDATE gamesite.users SET email = 'seyv3@gmail.com', password = '$2y$10$yXz1MsMaf9L6jKigngjyzuzmHgp89yfQKta0yvD6CVcA.cQVq5FH6' WHERE id = 3;
UPDATE gamesite.users SET email = 'tetradochka1488@gmail.com', password = '$2y$10$Qf6E9SxUbU8BjBeUHucqyuI/258th3WFhc6klfav147pY/qiIN5fO' WHERE id = 4;
UPDATE gamesite.users SET email = 'g@gmail.com', password = '$2y$10$L4nfHVyqlID7U06x5Nej5uTI3rjZyfMEh7zkbBxAUgRU/CtKS3GGu' WHERE id = 7;
UPDATE gamesite.users SET email = 'd@mail.ru', password = '$2y$10$GIHInfjWJWH51UdVKKHTSeS6zo/55wB31cQFhHQ66xe7WLK0pftoa' WHERE id = 8;
UPDATE gamesite.users SET email = 'sdfdsf@gadf.sfsdf', password = '$2y$10$6IlMr3c3zDqXYsAayRRxouL95/I2tgPMa1YNqVJbTmhC2uy7ifgpC' WHERE id = 9;
UPDATE gamesite.users SET email = 'nakmak1998@gmail.com', password = '$2y$10$NelsS902GWPWY3B63v1rE.5/Kt8zHcfNn6WG5Th2ChPsF7y/kRATK' WHERE id = 10;